export const jobCategories = [
  "Transportation",
  "Information Technology (IT)",
  "Engineering",
  "Healthcare",
  "Finance",
  "Education",
  "Sales",
  "Marketing",
  "Hospitality",
  "Customer Service",
  "Human Resources",
  "Retail",
  "Manufacturing",
  "Construction",
  "Design",
  "Media",
  "Legal",
  "Logistics",
  "Science",
  "Agriculture",
  "Non-profit",
  "Government",
  "Telecommunications",
  "Real Estate",
  "Research",
  "Art and Entertainment",
];
