export const places = [
  "Bucharest, RO",
  "Cluj-Napoca, RO",
  "Pitesti, RO",
  "Timisoara, RO",
  "Brasov, RO",
  "Chisinau, MD",
  "Paris, FR",
  "London, GB",
  "New York, US",
  "Los Angeles, US",
  "Chicago, US",
  "San Francisco, US",
  "Houston, US",
  "Miami, US",
  "Las Vegas, US",
  "Berlin, DE",
  "Hamburg, DE",
  "Munich, DE",
  "Cologne, DE",
  "Frankfurt, DE",
  "Stuttgart, DE",
  "Moscow, RU",
  "Saint Petersburg, RU",
  "Novosibirsk, RU",
  "Yekaterinburg, RU",
  "Kazan, RU",
  "Nizhny Novgorod, RU",
  "Mexico City, MX",
  "Guadalajara, MX",
  "Monterrey, MX",
  "Puebla, MX",
  "Rio de Janeiro, BR",
  "Sao Paulo, BR",
  "Brasília, BR",
  "Fortaleza, BR",
  "Dubai, AE",
  "Abu Dhabi, AE",
  "Doha, QA",
  "Kuwait City, KW",
  "Riyadh, SA",
  "Jeddah, SA",
  "Singapore, SG",
  "Stockholm, SE",
  "Gothenburg, SE",
  "Vienna, AT",
  "Salzburg, AT",
  "Athens, GR",
  "Thessaloniki, GR",
  "Bangkok, TH",
  "Chiang Mai, TH",
  "Toronto, CA",
  "Vancouver, CA",
  "Montreal, CA",
  "Ottawa, CA",
  "Quebec City, CA",
  "Sydney, AU",
  "Melbourne, AU",
  "Brisbane, AU",
  "Perth, AU",
  "Auckland, NZ",
  "Wellington, NZ",
  "Christchurch, NZ",
  "Dunedin, NZ",
  "Johannesburg, ZA",
  "Cape Town, ZA",
  "Durban, ZA",
  "Pretoria, ZA",
  "Lusaka, ZM",
  "Harare, ZW",
  "Gaborone, BW",
  "Windhoek, NA",
  "Accra, GH",
  "Abidjan, CI",
  "Lagos, NG",
  "Kinshasa, CD",
  "Kigali, RW",
  "Kampala, UG",
  "Addis Ababa, ET",
  "Dar es Salaam, TZ",
  "Khartoum, SD",
  "Cairo, EG",
];
